#165305726 Like and Dislike Article
andela/ah-the-immortals-frontend pull request #33
Opened 2019-06-17 14:28 UTC by Ogutu-Brian

#### What does this PR do?
* Adds like and dislike feature to articles
#### Description of Task to be completed?
* Unauthorized user should not be able to like an article
* An authorized user should like, unlike, dislike and remove dislike to an article
#### How should this be manually tested?
* After cloning the repo:
```
$ git checkout ft-like-dislike-article-165305726
$ npm run start:dev
```
#### What are the relevant pivotal tracker stories?
[#165305726](https://www.pivotaltracker.com/story/show/165305726)

2019-06-19 18:56 UTC, Amoswachira approved these changes

2019-06-19 23:29 UTC, IssaIan requested changes
Hello @Ogutu-Brian. During the testing of the application, it seems the app crashes at some point. Tried viewing the first and second article from heroku and this error occurs. Have a look and check what could be causing this.

![image](https://user-images.githubusercontent.com/41931013/59808037-29fad480-9303-11e9-8083-d422a78220da.png)

2019-06-20 04:44 UTC, Ogutu-Brian commented
> Hello @Ogutu-Brian. During the testing of the application, it seems the app crashes at some point. Tried viewing the first and second article from heroku and this error occurs. Have a look and check what could be causing this.
> 
> ![image](https://user-images.githubusercontent.com/41931013/59808037-29fad480-9303-11e9-8083-d422a78220da.png)

Okay. Thanks @IssaIan ,
Let me check and get back to you ASAP

2019-06-20 07:04 UTC, IssaIan approved these changes

2019-06-20 07:10 UTC, a-braham approved these changes

2019-06-20 15:48 UTC, merged