#165305723 Rate articles
andela/ah-the-immortals-frontend pull request #36
Opened 2019-06-19 08:37 UTC by Philipotieno

#### What does this PR do?
- Rate articles
#### Description of Task to be completed?
- Implement a 5 start rating of articles
- Get an average rating of an article
#### How should this be manually tested?
- `$ git clone https://github.com/andela/ah-the-immortals-frontend`
- `$ git checkout ft-rate-articles-165305723`
- `$ npm install`
- `$ npm run start:dev`
#### What are the relevant pivotal tracker stories?
[`#165305723`](https://www.pivotaltracker.com/n/projects/2326460/stories/165305723)
#### Screenshots
![image](https://user-images.githubusercontent.com/29012135/59749809-66d4b600-9286-11e9-9157-cd3f173cbc99.png)

2019-06-19 23:45 UTC, IssaIan reviewed
Is there a way of making the stars light in colour before a user submits the rating. The black color is confusing to the user as the user.

2019-06-20 16:55 UTC, Philipotieno reviewed
Fixed conflicts

2019-06-23 20:00 UTC, Ogutu-Brian commented
> Fix conflicts

Yes @Philipotieno ,
Please fix the conflicts

2019-06-23 20:10 UTC, Ogutu-Brian requested changes

2019-06-23 20:10 UTC, Ogutu-Brian commented on src/components/RateArticles/RateArtcles.jsx
> +    return !!currentUser?(
Hello @Philipotieno ,
When you negate !!currentUser==currentUser, you need not to use the double negation

2019-06-23 20:10 UTC, Ogutu-Brian commented on src/components/RateArticles/RateArtcles.jsx
> +    const { article, currentUser } = this.props;
Hello @Philipotieno ,
currentUser should be included in the props validation

2019-06-23 20:10 UTC, Ogutu-Brian commented on src/components/RateArticles/RateArtcles.jsx
> +        rating
Hello @Philipotieno ,
You are not using the state element `rating` so you could do away with it. On matters that, the method:
```
  onStarClick = nextValue => {
    const { article, starClick } = this.props;
    const slug = article.slug;
    starClick(slug, { rate: nextValue }, rating =>
      this.setState({
        rating
      })
    );
  };
```
In `RateArticles.jsx` is not actually being used.

2019-06-24 05:56 UTC, Philipotieno commented
@Ogutu-Brian thanks for that I
 am fixing all the hound Issues

2019-06-25 09:29 UTC, Ogutu-Brian approved these changes

2019-06-25 11:48 UTC, merged