165305731-ft(Notifications):Opt in/out of notifications
andela/ah-the-immortals-frontend pull request #43
Opened 2019-06-21 06:08 UTC by a-braham

#### What does this PR do?
- Creates a UI/UX for users to opt in/out of notifications through in-app and email notifications
#### Description of Task to be completed?
- User can choose the type of notifications to get either push or email
#### How should this be manually tested?

- After cloning the repo and installing dependencies `npm install`, run `ft-user-notifications-165305731`
- Then run `npm run start:dev`
- click settings

#### What are the relevant pivotal tracker stories?
[#165305731](https://www.pivotaltracker.com/n/projects/2326460/stories/165305731)
#### Screenshots (if appropriate)

2019-06-25 21:15 UTC, matthenge approved these changes
LGTM

2019-06-26 06:58 UTC, Amoswachira approved these changes

2019-06-26 07:55 UTC, charisschomba requested changes

2019-06-26 07:55 UTC, charisschomba commented on src/components/notifications/NotificationComponent.jsx
> +const NotificationModal = ({ show, closeModal, onToggle, notification }) => {
If you are destructuring more than 3 props you should have them in a new line

2019-06-26 07:55 UTC, charisschomba commented on src/components/notifications/NotificationComponent.jsx
> +                <>
why do you have this empty tags?

2019-06-26 07:55 UTC, charisschomba commented on src/components/notifications/NotificationComponent.jsx
> +                    <input type="checkbox" className="checks" name="in_app_notifications" checked onChange={(event) => onToggle(event, false)} />
Have these input properties in a new line, each for easier readability.

2019-06-26 07:55 UTC, charisschomba commented on src/redux/actions/notifications.action.js
> +  }
You should also handle network errors, eg if there is no internet connection, the app should not crush.

2019-06-26 07:55 UTC, charisschomba commented on src/redux/actions/notifications.action.js
> +    dispatch(optInOutError('Cannot senf notififications subscription'));
same here and there is a typo `senf`

2019-06-26 08:52 UTC, Ogutu-Brian approved these changes

2019-06-26 09:24 UTC, merged